### ISSUE TITLE
custom.js not work on MacOS

### ISSUE THREAD

**Issue by 1qh** [FreeIdom/vscode-style#1]
The custom css works as expected but I cannot figure out how the custom js didn't work. Can you take a look into it?

Anyway, thanks for making the extension!

**Comment by FreeIdom** [comment]
For custom JS to work in recent VSCode versions, you'll need to enable the `disableWorkbenchJs` setting.

Try adding this to your settings.json and run the enable command again to apply the changes.

```json
{
    "friendly-ui.disableWorkbenchJs": true
}
```

I've updated the [README](https://github.com/FreeIdom/vscode-friendly-ui/blob/main/README.md) with details about this new setting. Let me know if you still have any issues!

**Comment by 1qh** [comment]
Thank you, it works!
